const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/cart.controller");
const middleware = require("../../middlewares/client/cart.middleware");
const userMiddleware = require("../../middlewares/client/user.middleware");
router.post("/add/:id", userMiddleware.requireAuth ,controller.addPost);
router.get("/", userMiddleware.requireAuth ,controller.index);
router.get("/delete/:id/:price", userMiddleware.requireAuth,controller.delete);
router.patch("/update",userMiddleware.requireAuth ,controller.update);
module.exports = router;