const express = require('express');
const router = express.Router();
const controller = require('../../controllers/admin/role.controller.js');
router.get('/', controller.index);
router.get('/create', controller.createRole);
router.post('/create', controller.createRolePost);
router.get('/edit/:id', controller.editRole);
router.patch('/edit/:id', controller.editRolePatch);
router.get('/permissions', controller.permissions);
router.patch('/permissions', controller.permissionsPatch);
module.exports = router;